###################################################################################
# local

[local]
git = 'storage/git'     # Directory to store local git repositories

[local.aliases.text]
# The aliases.text map allows for case-sensitive simple text substitution between URLs
# requested by a gather of some kind and the URL actually used for the remote repository.
#
# This also affects the local storage location, as it follows the actual URL after
# substitution.
#
# All local.aliases.text substitutions are performed in the order listed below.
#

'git://git.buildroot.net/buildroot' = 'https://gitlab.com/buildroot.org/buildroot.git'

[local.aliases.regex]
# The aliases.regex map allows for Python regex substitution.  This is more powerful,
# but more complex, than simple text substitution.  These substitutions are case-insensitive.
#
# The use of single-quote strings to avoid escaping is highly recommended here.
#
# All local.aliases.regex are performed in the order listed below, after local.aliases.text
# substitutions have been performed.

'\bosvvm/'  = 'OSVVM/'      # Always capitalize OSVVM an organiation
'\bwww\.'   = ''            # Remove any www. from URLs.

###################################################################################
# gather

[gather]
# Set this true to update all git repositories in the local.git storage, even
# if nothing else calls for them.  Not yet implemented.
# local = true

# URLs for specific remote repositories to also fetch.
# remotes = ['https://github.com/highland-technology-inc/linkrottie.git]

# gather.github entries fetch all of a given organization's repositories using
# the Github API.
# 
[gather.github.highland-technology-inc]
auth_key_file = './API_KEY'     # File containing the API authentication key
dry_run = false                 # Set dry_run to only see which repositories would be fetched, but not do it.

# The ignore list is for repositories that should not be gathered.
ignore = ['OsvvmLibraries', 'FreeRTOS-Kernel', 'STM32CubeF2', 'buildroot']